name: echo
on:
 push:
   branches:
    - main
# workflow_dispatch:
#  pull_request:
#    types: [closed]
#    branches:
#      - main    
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello heree"
  build2:
    needs: build1
    runs-on: ubuntu-latest
    steps:
      - name: bye
        run: echo "Bye here"   
      - name: success step
        run: |
          exit 1
          echo "This is the End.."
          coninue-on-error: true
      - name: display
        run: |
          echo "This is  ${{ github.ref}}"
          echo "This is  ${{ github.sha}}"
      - name: display 2    
        run: |
          echo "Author: ${{ github.actor}}"
  echo:
    needs: build2
    runs-on: ubuntu-latest
    steps:
      - name: show trigger
        run: |
          echo "This is triggerd by an ${{ github.event_name}} event.."
          echo "Runner OS: $RUNNER_OS"