name: Display Information
run-name: Run Details | ${{inputs.debug && 'ON' || 'OFF'}}
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  flow_run: 'workflow'        
jobs:
  app1:
    runs-on: ubuntu-latest
    steps:
      - name: '[Debug] Print start up data'
        if: ${{ inputs.debug }}
        run: |
          echo " Trigger by ${{ github.event_name}} event" 
          echo "Branch : ${{ github.ref}}"
          echo "Actor : ${{ github.actor}}"
          echo "OS: ${{ runner.os}}"
  app2:
    runs-on: ubuntu-latest
    steps:    
      - name: '[Debug] print from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: |
          echo "This is main branch"
      - name: 'Print Hello'
        run: |
          echo "Hello world"
  build1:
    needs: app2
    runs-on: ubuntu-latest
    env:
      flow_run: 'job'
    steps:                
      - name: Display all
        run: |
          echo " Trigger by ${{ github.event_name}} event" 
          echo "Ref : ${{ github.ref}}"
          echo "SHA : ${{ github.sha}}"
          echo "Actor : ${{ github.actor}}"
          echo "workflow: ${{ github.workflow}}"
          echo "Run ID : ${{ github.run_id}}"
          echo "Run num : ${{ github.run_number}}" 
      - name: variable
        env:
          flow_run: 'step'
        run: |
          echo "variable value: ${{vars.MY_VAR}}"
          echo " env: ${{ env.flow_run}}"
      - run: |
          echo "env: ${{ env.flow_run}}"
  build2:
    needs: build1
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "env: ${{ env.flow_run}}"
