name: Display Information
run-name: Run Details | ${{inputs.debug}}
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:                
      - name: Display all
        run: |
          echo " Trigger by ${{ github.event_name}} event" 
          echo "Ref : ${{ github.ref}}"
          echo "SHA : ${{ github.sha}}"
          echo "Actor : ${{ github.actor}}"
          echo "workflow: ${{ github.workflow}}"
          echo "Run ID : ${{ github.run_id}}"
          echo "Run num : ${{ github.run_number}}" 
      - name: variable
        run: |
          echo "variable value: ${{vars.MY_VAR}}"