name: Funstion CICD
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: sleep
        run: sleep 10
        if: ${{ success()}}
      - name: sucess step
        run: echo "Sucess step"
      - name: fail test
        run: exit 1
        if: ${{ failure()}}        
      - name: fail step
        run: echo "This is fail step"
        if: ${{ success()}}
      - name: sucess step
        run: echo "Sucess step"
        if: ${{ !cancelled() }}
      - name: execute step
        run: echo "Run if not cancel, check test step if failed"
        if: ${{ cancelled() }}
      - name: cancel step  
        run: echo "This is cancel step"
          