name: Function CICD
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: sleep
        run: sleep 10        
      - name: sucess step
        if: ${{ success()}}
        run: echo "Sucess step"
      - name: fail test
        run: exit 1                
      - name: fail step
        if: ${{ failure()}}
        run: echo "This is fail step"        
      - name: sucess step
        if: ${{ success()}}
        run: echo "Sucess step"        
      - name: execute step
        if: ${{ !cancelled() }}
        run: echo "Run if not cancel, check test step if failed"        
      - name: cancel step  
        if: ${{ cancelled() }}
        run: echo "This is cancel step"
          