name: React CI/CD Level 2
run-name: React app
on: 
  workflow_dispatch:    
#  push:
#    branches:
#     - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: using_actions/react-app   
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm ci               
      - name: Build React app
        run: |
          npm run build
          exit 1
  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: using_actions/react-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy
        run: echo "Deploying React app"
